baseURL = 'https://nagstamon.de/'
languageCode = 'en-us'
title = 'Nagstamon'

[params]
  description = 'Nagstamon status monitor for the desktop.'
  email = 'contact@nagstamon.de'
  twitter_username = 'nagstamon'
  github_username = 'henriwahl'
  repository = 'henriwahl/nagstamon'

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[outputFormats.RSS]
  baseName = 'feed'
  mediaType = 'application/rss+xml'

[mediaTypes."application/rss+xml"]
  suffixes = ["xml"]

[permalinks]
  news = '/:slug/'

[menu]
  [[menu.main]]
    name = 'News'
    url = '/news/'
    weight = 1
  [[menu.main]]
    name = 'Download'
    url = '/download/'
    weight = 2
  [[menu.main]]
    name = 'Features'
    url = '/features/'
    weight = 3
  [[menu.main]]
    name = 'Documentation'
    url = '/documentation/'
    weight = 4
